### ISSUE TITLE
`debate.sty` not found

### ISSUE THREAD

**Issue by kir0ul** [yegor256/debate#13]
Hi,
I'm missing the `debate.sty` file, which on the README points to https://raw.githubusercontent.com/yegor256/debate/gh-pages/debate/debate.sty, but I get a `404: Not Found` when I try to access this file.
Any chance it could be updated? I'm happy to make a PR in case.
Thanks!

**Comment by yegor256** [comment]
@kir0ul I believe it's fixed, please try again

**Comment by kir0ul** [comment]
Yes, thanks! :pray:
