### ISSUE TITLE
Will be cool to use \begin{...} inside

### ISSUE THREAD

**Issue by MikhailLipanin** [yegor256/debate#8]
It will be cool if we can do this:
```
\debate[User]{ I suggest using this code snippet:
\begin{ffcode}
[] > main
  stdout "Hello"
\end{ffcode}
}
```
@yegor256 WDYT?

**Comment by yegor256** [comment]
@MikhailLipanin it's technically impossible in LaTeX. We can't pass an environment into a command, to my knowledge.

**Comment by MikhailLipanin** [comment]
@yegor256, Okay, I'm closing
